name: Citation Validation

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths:
      - 'CITATION.cff'
  pull_request:
    branches:
      - '**'
    paths:
      - 'CITATION.cff'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  get-ruby-version:
    name: Get Latest Ruby Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-language-versions.outputs.latest-versions }}

    steps:
      - name: Get Required Version
        uses: ActionsToolbox/get-language-versions-action@446919617fd774095b5dd3ed71c39dd3fd0d8f4f  # v0.1.3
        id: get-language-versions
        with:
          language: "ruby"
          highest-only: true
          remove-patch-version: true

  awesomebot:
    name: Awesomebot
    needs: get-ruby-version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Setup Ruby ${{ needs.get-ruby-version.outputs.version }}
        uses: ruby/setup-ruby@32110d4e311bd8996b2a82bf2a43b714ccc91777  # v1.221.0
        with:
          ruby-version: ${{ needs.get-ruby-version.outputs.version }}

      - name: Perform Awesomebot Analysis
        env:
          FLAGS: "default"
          WHITELIST: "https://img.shields.io"
          INCLUDE_FILES: "CITATION.cff"
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/awesomebot/master/pipeline.sh)

  validate-citation-file:
    name: Validate CITATION.cff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Validate CITATION.cff
        uses: citation-file-format/cffconvert-github-action@4cf11baa70a673bfdf9dad0acc7ee33b3f4b6084  # v2.0.0
        with:
            args: "--validate"

  citation-validation-pipeline:
    if: always()
    name: Citation Validation Pipeline
    needs:
      - awesomebot
      - validate-citation-file
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Check Job Statuses
        run: .github/scripts/check-jobs.sh '${{ toJson(needs) }}'
