name: Repository Validation

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - '**/*.md'
      - '**/*.cff'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'
      - '**/*.cff'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  get-go-version:
    name: Get Latest Go Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-language-versions.outputs.latest-versions }}

    steps:
      - name: Get Required Versions
        uses: ActionsToolbox/get-language-versions-action@446919617fd774095b5dd3ed71c39dd3fd0d8f4f  # V0.1.3
        id: get-language-versions
        with:
          language: "go"
          highest-only: true
          remove-patch-version: true

  get-python-version:
    name: Get Latest Python Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-language-versions.outputs.latest-versions }}

    steps:
      - name: Get Required Versions
        uses: ActionsToolbox/get-language-versions-action@446919617fd774095b5dd3ed71c39dd3fd0d8f4f  # V0.1.3
        id: get-language-versions
        with:
          language: "python"
          highest-only: true
          remove-patch-version: true

  action-lint:
    name: Action Lint
    needs: get-go-version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # V6.0.0

      - name: Setup Go ${{ needs.get-go-version.outputs.version }}
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # V5.5.0
        with:
          go-version: ${{ needs.get-go-version.outputs.version }}

      - name: Perform Action Lint Analysis
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/action-lint/master/pipeline.sh)

  yaml-lint:
    name: YAML Lint
    needs: get-python-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # V6.0.0

      - name: Set up Python ${{ needs.get-python-version.outputs.version }}
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # V5.6.0
        with:
          python-version: ${{ needs.get-python-version.outputs.version }}

      - name: Perform YAML Lint Analysis
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/yaml-lint/master/pipeline.sh)

  repository-validation-pipeline:
    if: always()
    name: Repository Validation Pipeline
    needs:
      - action-lint
      - yaml-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # V6.0.0

      - name: Check Job Statuses
        run: .github/scripts/check-jobs.sh '${{ toJson(needs) }}'
